package com.example.mainapphunar.products.view_model

import com.example.mainapphunar.types.CategoryType
import com.example.mainapphunar.types.ProductType

class Repository {
    var productList = listOf<ProductType>(
        ProductType(
            2,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Suvenier",
            null,
            null,
            353,
            "g",
            "tut daraxti",
            null,
            null,
            "1000000.00",
            true,
            false,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA12.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA11.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA10.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA9.jpg"
        ),
        ProductType(
            4,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Soat",
            null,
            null,
            1803,
            "g",
            "Yasin daraxti",
            null,
            null,
            "100000.00",
            true,
            true,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA17.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA18.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA19.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA20.jpg"
        ),
        ProductType(
            6,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Mevalar uchun idish",
            null,
            null,
            354,
            "g",
            "Chinor daraxti",
            null,
            null,
            "100000.00",
            true,
            true,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA25.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA26.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA27.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA28.jpg"
        ),
        ProductType(
            2,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Suvenier",
            null,
            null,
            353,
            "g",
            "tut daraxti",
            null,
            null,
            "1000000.00",
            true,
            true,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA12.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA11.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA10.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA9.jpg"
        ),
        ProductType(
            4,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Soat",
            null,
            null,
            1803,
            "g",
            "Yasin daraxti",
            null,
            null,
            "100000.00",
            true,
            false,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA17.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA18.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA19.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA20.jpg"
        ),
        ProductType(
            6,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Mevalar uchun idish",
            null,
            null,
            354,
            "g",
            "Chinor daraxti",
            null,
            null,
            "100000.00",
            true,
            true,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA25.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA26.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA27.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA28.jpg"
        ),
        ProductType(
            2,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Suvenier",
            null,
            null,
            353,
            "g",
            "tut daraxti",
            null,
            null,
            "1000000.00",
            true,
            true,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA12.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA11.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA10.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA9.jpg"
        ),
        ProductType(
            4,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Soat",
            null,
            null,
            1803,
            "g",
            "Yasin daraxti",
            null,
            null,
            "100000.00",
            true,
            false,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA17.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA18.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA19.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA20.jpg"
        ),
        ProductType(
            6,
            "Yog'och o'ymakorligi",
            null,
            null,
            13,
            "Mevalar uchun idish",
            null,
            null,
            354,
            "g",
            "Chinor daraxti",
            null,
            null,
            "100000.00",
            true,
            false,
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA25.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA26.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA27.jpg",
            "https://edumonitoring.uz/media/product/image/%D0%A0%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA28.jpg"
        )
    )



    var categoryList = listOf(
        CategoryType(
            3,
            "Milliy o'yinchoqlar yasash",
            null,
            null,
            "https://edumonitoring.uz/media/hunar_type/Milliy%20o'yinchoqlar%20yasash/Milliy_oyinchoqlar_yasash.jpg",
            "Oʻyinchoq asosan bolalar oʻynashi uchun yasalgan buyumdir. Oʻyinchoqlarni yasashda yogʻoch, gil, qogʻoz va plastmassa kabi turli xil materiallar qoʻllaniladi. Baʼzi oʻyinchoqlar asosan kolleksionerlar buyumlari oʻlaroq ishlab chiqarilib, faqat namoyish etish uchun moʻljallangan boʻladi. Oʻyinchoqlar asosan kichik yoshdagilar uchun ishlab chiqariladi. Hozirga qadar maʼlum boʻlgan eng eski oʻyinchoq bu qoʻgʻirchoq boʻlib, uning yoshi 4 000 yosh deb taxmin qilinadi. Qush hushtak o'yinchoq O'yinchoq - bu dunyoni o'ynash va o'rganish uchun ob'ekt bilan o'zaro ta'sir qilish uchun mo'ljallangan ob'ekt.",
            null,
            null
        ),

    )
}